### ISSUE TITLE
npm start.js contains windows line endings

### ISSUE THREAD

**Issue by bastianh** [screeps/storage#2]
Hi,

it's not possible to simply start the storage service because the `start.js` file contains windows file endings:

> env: node\r: No such file or directory

Thanks for screeps ;)

**Comment by AlinaNova21** [comment]
Ran into this issue today trying to write examples on deploying individual modules. The github repo has the correct line endings, what I suspect happened is the repo was checked out and published from a windows PC where the git client was configured to auto-convert line endings. A version bump and republish from a system that doesn't convert endings should solve this.

**Comment by artch** [comment]
Fixed in 3.1.4. 

Also see https://github.com/npm/npm/pull/16634 - this should be automatically handled by npm version >= 5.4.0.
