### ISSUE TITLE
db.databaseVersion is NOT your DB layout version...

### ISSUE THREAD

**Issue by mloftis** [screeps/storage#3]
Every restart will re-run the upgrade code causing money to multiply as the lib/db.js appears to incorrectly look at (and set) the db.databaseVersion property which is apparently internal to lokiJS.  It is setting this to 1.5 during load, which will ALWAYS be < 2 -- lokiJS certainly uses it itself to check for some internal layout changes.

**Comment by artch** [comment]
They [commented it out](https://github.com/techfort/LokiJS/blob/41f9e19fb460a86a8e452deb269f0c5a49e5952d/src/lokijs.js#L1527-L1531) in 1.5 release. Make sure you use LokiJS 1.4.2 as defined in [`package.json`](https://github.com/screeps/storage/blob/master/package.json).

**Comment by mloftis** [comment]
But they unconditionally set it to 1.5 at [line #745](https://github.com/techfort/LokiJS/blob/41f9e19fb460a86a8e452deb269f0c5a49e5952d/src/lokijs.js#L745)
and indeed that is what db.databaseVersion is when you start the server (which was causing my behavior).  The included storage package.json allows for anything after 1.4.2 to less than 2.0.0 (and the npm install behavior) pulls in 1.5.1 accordingly.

Moreover it's pretty clear lokiJS intends that to be an internal to lokiJS value for it's own housekeeping use, even in 1.4.x

**Comment by mloftis** [comment]
So, alternative fix if you really still want to use the lokiJS db.databaseVersion would be to pin yourself at 1.4.2, or, some other semver expression that keeps it within 1.4.x.

**Comment by artch** [comment]
I have [requested](https://github.com/techfort/LokiJS/issues/623) a clarification on `databaseVersion` usage. Meanwhile, I'll update `package.json` to strict 1.4.2.
